== Client Side Setup

=== Windows

==== Choice of editor: Alacritty

The standard editor in windows is the cmd application that provides a cmd-shell or a powershell. The issue that promted me to install a different editor was, that I could not overwrite the keyboard comnbinbation `Ctrl-z` somehow. As on many programs this is the undo-function I hit this quite frequently without intending to and ended my docker session which meant that I lost my edits. With Alacritty I managed to acchieve a setup with all my requirements quickly. Alacritty was the first editor I tried out, so there might be vailid alternatives I am unaware of.

==== reference configuration

This is my configuration (for details where to put it look for the documentation for Alacritty on the web)

[source]
-------
[font]
size = 14.0

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold Italic"

[[keyboard.bindings]]
action = "None"
key = "Z"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "Z"
mods = "Control"
[
[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

window.dimensions]
columns = 120
lines = 30

# Colors (add this to your alacritty.toml)
[colors]
# Default colors
[colors.primary]
background = '0x000000'
foreground = '0xe5e5e5'

# Normal colors
[colors.normal]
black = '0x000000'
red = '0xff5555'
green = '0x50fa7b'
yellow = '0xf1fa8c'
#blue = '0xbd93f9'
blue = '0x0000ff'   # Darker blue for better readability
magenta = '0xff79c6'
cyan = '0x8be9fd'
white = '0xbfbfbf'

# Bright colors
[colors.bright]
black = '0x4d4d4d'
red = '0xff6e6e'
green = '0x69ff94'
yellow = '0xffffa5'
blue = '0xd6acff'
magenta = '0xff92d0'
cyan = '0xa4ffff'
white = '0xe6e6e6'
-------

Lets go through it in detail

* The font size is purely based on my prefernce

* to display the file tree in neovims "neotree" plugin in a somewhat advanced way I needed 3 requisites.

   ** install UTF-8 compatible locale in the container (compare Dockerfile)
   ** install a font that offers special unicode characters (e.g. open and closed folders) to the windows system
   ** configure that font in the alacritty.toml

* keyboard bindings

   ** suppress the key combination `Ctrl-z` to avoid leaving the docker session unintentionally
   ** define a way to copy the clipboard on my local machine into nvim (C+Ctrl+Shift)

* window dimensions are purely personal preference

* I had to aajdust the colors slightly to have a good readability under unix when moving in the shell. In my case I had unreadable folders due to a lack of contrast between fore and background

==== prerequisits

The only additional thing was to download and install a nerd font. This is a special group of monospace font containing a high number of glyphes. 

I downloaded Jetbrains nerd font from a git repo as a zip, unpack it and install it by right click on the system.

you can preview the fonds on the system by using the app "settings" and in there the section "fonts".

== Copy and Paste between editor in the container and the host machine

Copy and paste within nvim works via internal buffers and by itself has no interaction with the clipboard on my host machine. This poses a problem if I vant to "copy and paste" content from an application on my host machine (e.g. a browser window) to nvim in my docker container or if I want to do this between different nvim sessions in distinct containers.

I do start neovim within a tmux session - this in combination with the tmux setting in this repo allows we to use the buffer created when copying something with the right-mouse-click-action is inserted into the clipboard of my host machine. This enables the direction nvim to host machine.

The editor configuration contains a section dedicated to cut and paste. 

[source]
--------
[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"
--------

this should allow to copy and paste independently of tmux on the level of the terminal. In my environment, this does work for paste - unfortunately it does not work for the other way, but here I have the solution above. Thus copy and paste works (somehow) in both directions. There might be more consistent solutions. 

== Neo-tree Icons

[cols="1,1,1", options="header"]
|===
| Icon | Unicode | Significance

|  | `U+F492` | Configuration or settings file (.env)
|  | `U+E702` | Git-related file (.gitattributes, .gitignore)
| 󰡨 | `U+ECA8` | Docker-related file (docker-compose.yml)
|  | `U+E615` | General configuration or settings file (docker-compose.debug.yml)
|  | `U+E5FF` | Folder (closed)
|  | `U+E5FE` | Folder (open)
|  | `U+F15C` | File
|===

